export interface ToolFaq { q: string; a: string; }
export interface ToolSection { heading: string; body: string; }

export type ToolComponent =
  | 'percentage-calculator' | 'grade-calculator' | 'gpa-calculator'
  | 'attendance-calculator' | 'average-calculator' | 'study-timer' | 'unit-converter'
  | 'password-generator' | 'text-counter' | 'qr-generator'
  | 'ohms-law-calculator' | 'kinetic-energy-calculator' | 'potential-energy-calculator';

export interface Tool {
  slug: string; title: string; category: string; shortDescription: string;
  seoTitle: string; seoDescription: string; featured: boolean;
  status: 'draft' | 'published'; component: ToolComponent;
  intro: string; sections: ToolSection[]; faqs: ToolFaq[];
}

export const tools: Tool[] = [
  { slug: 'percentage-calculator', title: 'Percentage Calculator', category: 'student-tools', shortDescription: 'Calculate X% of a number, what percent X is of Y, and percentage change.', seoTitle: 'Percentage Calculator — Free Online Tool | MarqDesk', seoDescription: 'Free percentage calculator with three modes.', featured: true, status: 'published', component: 'percentage-calculator', intro: 'Use this free percentage calculator to solve the three most common percentage problems.', sections: [{ heading: 'What is a percentage?', body: 'A percentage is a way of expressing a number as a fraction of 100.' }], faqs: [{ q: 'Is this calculator free?', a: 'Yes, it runs entirely in your browser.' }] },
  { slug: 'grade-calculator', title: 'Grade Calculator', category: 'student-tools', shortDescription: 'Convert marks obtained into a percentage and a letter grade.', seoTitle: 'Grade Calculator — Marks to Percentage and Letter Grade | MarqDesk', seoDescription: 'Free grade calculator for students.', featured: false, status: 'published', component: 'grade-calculator', intro: 'Enter marks obtained and maximum possible marks to see your percentage and letter grade.', sections: [{ heading: 'Grading scale used', body: 'A+ = 90–100%, A = 80–89.99%, B = 70–79.99%, C = 60–69.99%, D = 50–59.99%, F = below 50%.' }], faqs: [{ q: 'Is this grading scale universal?', a: 'No. Scales differ by institution.' }] },
  { slug: 'gpa-calculator', title: 'GPA Calculator', category: 'student-tools', shortDescription: 'Calculate your GPA on the 4.0 scale from letter grades and credit hours.', seoTitle: 'GPA Calculator — 4.0 Scale with Credits | MarqDesk', seoDescription: 'Free GPA calculator for students.', featured: false, status: 'published', component: 'gpa-calculator', intro: 'Add one row per course, choose the letter grade, and calculate your GPA on the 4.0 scale.', sections: [{ heading: 'Grade point values used', body: 'A = 4.0, A− = 3.7, B+ = 3.3, B = 3.0, B− = 2.7, C+ = 2.3, C = 2.0, C− = 1.7, D+ = 1.3, D = 1.0, F = 0.0.' }], faqs: [{ q: 'Which grading scale is used?', a: 'The common 4.0 scale with plus and minus grades.' }] },
  { slug: 'attendance-calculator', title: 'Attendance Calculator', category: 'student-tools', shortDescription: 'Calculate your current attendance percentage and classes needed/skippable.', seoTitle: 'Attendance Calculator — Reach Your Target Percentage | MarqDesk', seoDescription: 'Free attendance calculator for students.', featured: false, status: 'published', component: 'attendance-calculator', intro: 'Find out how many consecutive classes you need to attend, or can safely skip, to hit your target.', sections: [{ heading: 'How it works', body: 'The calculator compares your current ratio against your target percentage.' }], faqs: [{ q: 'What is the default target?', a: '75%, which is a common university requirement.' }] },
  { slug: 'average-calculator', title: 'Average Calculator', category: 'student-tools', shortDescription: 'Calculate the mean, sum, and count for a list of numbers.', seoTitle: 'Average Calculator — Mean, Sum, and Count | MarqDesk', seoDescription: 'Free average calculator.', featured: false, status: 'published', component: 'average-calculator', intro: 'Add as many numbers as you need to instantly compute the mathematical mean, sum, and count.', sections: [{ heading: 'The formula', body: 'Mean = (Sum of all values) ÷ (Number of values).' }], faqs: [{ q: 'How many numbers can I add?', a: 'Up to 50 numbers at once.' }] },
  { slug: 'study-timer', title: 'Study Timer', category: 'student-tools', shortDescription: 'A simple Pomodoro-style focus timer to help you study effectively.', seoTitle: 'Study Timer — Free Pomodoro Focus Timer | MarqDesk', seoDescription: 'Free online study timer with 25-minute focus and 5-minute break modes.', featured: false, status: 'published', component: 'study-timer', intro: 'Break your study sessions into focused 25-minute intervals with 5-minute breaks.', sections: [{ heading: 'What is the Pomodoro technique?', body: 'A time management method that uses a timer to break work into intervals separated by short breaks.' }], faqs: [{ q: 'Does the timer keep running if I switch tabs?', a: 'Yes, as long as this page remains open in your browser.' }] },
  { slug: 'unit-converter', title: 'Unit Converter', category: 'student-tools', shortDescription: 'Convert between common units of length, mass, and temperature instantly.', seoTitle: 'Unit Converter — Length, Mass, and Temperature | MarqDesk', seoDescription: 'Free online unit converter for length, mass, and temperature.', featured: false, status: 'published', component: 'unit-converter', intro: 'Quickly convert between metric and imperial units. The conversion happens live as you type.', sections: [{ heading: 'Supported units', body: 'Length: m, cm, km, in, ft, mi. Mass: kg, g, lb, oz. Temperature: C, F, K.' }], faqs: [{ q: 'Are the conversion factors exact?', a: 'Yes, standard international conversion constants are used.' }] },
  { slug: 'password-generator', title: 'Password Generator', category: 'general-utilities', shortDescription: 'Create strong, random passwords with customizable length and character types.', seoTitle: 'Password Generator — Create Strong Passwords | MarqDesk', seoDescription: 'Free password generator that creates strong random passwords using your browser’s secure random number generator.', featured: false, status: 'published', component: 'password-generator', intro: 'Generate strong, random passwords entirely in your browser.', sections: [{ heading: 'How it works', body: 'The generator uses your browser’s cryptographically secure random number generator.' }], faqs: [{ q: 'Is my generated password sent to a server?', a: 'No. Generation happens locally on your device.' }] },
  { slug: 'text-counter', title: 'Text Counter', category: 'general-utilities', shortDescription: 'Count words, characters, sentences, and paragraphs, and estimate reading time.', seoTitle: 'Text Counter — Word and Character Counter | MarqDesk', seoDescription: 'Free online text counter that counts words, characters, sentences, and paragraphs.', featured: false, status: 'published', component: 'text-counter', intro: 'Type or paste any text and see live counts of words, characters, sentences, and paragraphs.', sections: [{ heading: 'How counting works', body: 'Words are groups of characters separated by whitespace.' }], faqs: [{ q: 'Is my text uploaded anywhere?', a: 'No. Counting happens live in your browser.' }] },
  { slug: 'qr-generator', title: 'QR Code Generator', category: 'general-utilities', shortDescription: 'Create custom QR codes for URLs, text, and Wi-Fi passwords with adjustable size and colors.', seoTitle: 'QR Code Generator — Create Custom QR Codes | MarqDesk', seoDescription: 'Free online QR code generator. Create custom QR codes with adjustable size, error correction, and colors.', featured: false, status: 'published', component: 'qr-generator', intro: 'Generate custom QR codes instantly for any text or URL.', sections: [{ heading: 'What is error correction?', body: 'QR codes contain redundant data that allows them to be scanned even if partially damaged.' }], faqs: [{ q: 'Is my text sent to a server?', a: 'No. The QR code is generated locally in your browser.' }] },
  { slug: 'ohms-law-calculator', title: "Ohm's Law Calculator", category: 'physics-tools', shortDescription: "Calculate Voltage, Current, or Resistance using Ohm's Law (V = IR).", seoTitle: "Ohm's Law Calculator — Free V, I, R Calculator | MarqDesk", seoDescription: "Free online Ohm's Law calculator. Enter any two values (Voltage, Current, Resistance) to instantly calculate the third.", featured: false, status: 'published', component: 'ohms-law-calculator', intro: "Enter any two known values and leave the third blank. This calculator uses Ohm's Law (V = I × R) to find the missing electrical property.", sections: [{ heading: "Ohm's Law Formula", body: "Voltage (V) = Current (I) × Resistance (R). Current (I) = Voltage (V) / Resistance (R). Resistance (R) = Voltage (V) / Current (I)." }], faqs: [{ q: 'What are the standard units?', a: 'Voltage is measured in Volts (V), Current in Amperes (A), and Resistance in Ohms (Ω).' }] },
  { slug: 'kinetic-energy-calculator', title: 'Kinetic Energy Calculator', category: 'physics-tools', shortDescription: 'Calculate the kinetic energy of an object based on its mass and velocity (KE = ½mv²).', seoTitle: 'Kinetic Energy Calculator — Free Physics Tool | MarqDesk', seoDescription: 'Free kinetic energy calculator. Enter mass and velocity to calculate kinetic energy in Joules instantly.', featured: false, status: 'published', component: 'kinetic-energy-calculator', intro: 'Calculate the energy an object possesses due to its motion. Enter the mass in kilograms and velocity in meters per second.', sections: [{ heading: 'The Formula', body: 'Kinetic Energy (KE) = ½ × mass × velocity². The result is expressed in Joules (J).' }], faqs: [{ q: 'Does velocity direction matter?', a: 'No. Because velocity is squared in the formula, the direction of motion does not affect the kinetic energy.' }] },
  { slug: 'potential-energy-calculator', title: 'Potential Energy Calculator', category: 'physics-tools', shortDescription: 'Calculate gravitational potential energy based on mass, height, and gravity (PE = mgh).', seoTitle: 'Potential Energy Calculator — Free Physics Tool | MarqDesk', seoDescription: 'Free gravitational potential energy calculator. Enter mass, height, and gravity to calculate potential energy in Joules.', featured: false, status: 'published', component: 'potential-energy-calculator', intro: 'Calculate the gravitational potential energy of an object relative to a reference point. The default gravity is set to Earth (9.81 m/s²), but you can change it for other planets.', sections: [{ heading: 'The Formula', body: 'Potential Energy (PE) = mass × gravity × height. The result is expressed in Joules (J).' }], faqs: [{ q: 'Can I calculate potential energy on the Moon?', a: 'Yes! Just change the gravity input to 1.62 m/s², which is the gravitational acceleration on the Moon.' }] },
];

export const publishedTools = tools.filter((t) => t.status === 'published');
export function getTool(slug: string): Tool | undefined { return publishedTools.find((t) => t.slug === slug); }
